name: Update Candles

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-candles:
    strategy:
      matrix:
        exchange: ["binanceus", "coinbase", "gemini", "kraken"]
        symbol: ["BTC/USD", "ETH/USD"]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Fetch and update candles
      uses: nick-fields/retry@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          python -m tickr.fetch_candles \
            --exchange=${{ matrix.exchange }} \
            --symbol=${{ matrix.symbol }} \
            --data_directory=data
