name: Update Candles

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-candles:
    strategy:
      matrix:
        exchange: ["binanceus", "coinbase", "gemini", "kraken"]
        symbol: ["BTC/USD", "ETH/USD"]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Set data directory
      run: echo "DATA_DIR=data/${{ matrix.exchange }}" >> $GITHUB_ENV

    - name: Fetch and update candles
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          # Update the local repository to the latest commit
          git pull

          # Fetch candle data for the specified exchange and symbol
          python -m tickr.fetch_candles \
            --exchange=${{ matrix.exchange }} \
            --symbol=${{ matrix.symbol }} \
            --data_directory=${DATA_DIR}

          # Stage all changes in the data directory
          git add ${DATA_DIR}/*

          # Check if there are any changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            # Commit the changes with a descriptive message
            git commit -m "chore(candles): Updated candle data for ${{ matrix.symbol }} on ${{ matrix.exchange }}. Frequency: 1m"
            # Push the commit to the main branch
            git push origin main
          else
            # Inform that there are no changes to commit
            echo "No changes to commit"
          fi
