name: Update Candles and Update Version

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-candles:
    strategy:
      matrix:
        exchange: ["kraken"]
        symbol: ["BTC-USD", "ETH-USD"]
        timeframe: ['1m', '5m', '15m', '1h', '6h', '12h', '1d', '1w']
          
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Fetch and update candles
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
      run: |
        python -m 'tickr.fetch_candles' \
          --exchange=${{ matrix.exchange }} \
          --symbol=${{ matrix.symbol }} \
          --timeframe=${{ exchange.timeframe }}

    - name: Semantic Version
      id: version
      uses: paulhatch/semantic-version@v5.3.0
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
        enable_prerelease_mode: true

    - name: Push Tag
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      run: |
        git tag ${{ steps.version.outputs.version_tag }}
        git push https://$GITHUB_ACTOR:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }} --tags
