name: Update Candles

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-candles:
    strategy:
      matrix:
        exchange: ["binanceus", "coinbase", "gemini", "kraken"]
        symbol: ["BTC/USD", "ETH/USD"]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Fetch and update candles
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          python -m tickr.fetch_candles \
            --exchange=${{ matrix.exchange }} \
            --symbol=${{ matrix.symbol }} \
            --data_directory=data

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Commit Changes
      run: |
        git add hubitat_lock_manager/version.py
        git commit -m "chore: Update candles. | Exchange: ${{ matrix.exchange }} | Symbol: =${{ matrix.symbol }}"
        git push origin main
