name: Update Candles

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-candles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Fetch candles serially
      run: |
        # Define arrays of exchanges and symbols
        exchanges=("binanceus" "coinbase" "gemini" "kraken")
        symbols=("BTC/USD" "ETH/USD")

        # Loop over each exchange and symbol combination
        for exchange in "${exchanges[@]}"; do
          for symbol in "${symbols[@]}"; do
            echo "Processing $symbol on $exchange"

            # Set data directory
            DATA_DIR="data/$exchange"

            # Fetch candle data
            python -m tickr.fetch_candles \
              --exchange="$exchange" \
              --symbol="$symbol" \
              --data_directory="$DATA_DIR"
          done
        done

    - name: Stage changes
      run: |
        # Stage all changes in the data directory
        git add data/*

    - name: Commit changes
      run: |
        # Check if there are any changes to commit
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          # Commit the changes with a descriptive message
          git commit -m "chore(candles): Updated candle data for all exchanges and symbols. Frequency: 1m"
        fi

    - name: Push changes
      if: success() && steps.commit-changes.outputs.changes_committed == 'true'
      run: |
        # Push the commit to the main branch
        git push origin main
